### PR TITLE
feat(core): Nx 11 compatibility with new lib separation for xplat

### PR DESCRIPTION
**Pull request by NathanWalker**
closes https://github.com/nstudio/xplat/issues/226

### CODE REVIEW

**Review by kattsushi — COMMENTED** [review]
🚀

**Comment by NathanWalker** [comment]
A webpack.config adjustment is needed to support the new setup for {N} - We will be publishing some updates on Friday and once the @nativescript/webpack update is out we can get at least an `rc` going of this if not the final version.

This is one of biggest updates to xplat since the beginning. It reigns in sweeping consistency with the "Nx way" organizing xplat architecture in `libs` all separated as distinct Nx libs with ability to be fully involved with dep-graph, linting, affected scripts, tests. This also improves TS resolution and IDE speed with intellisense.

Most likely an initial 11.0.0 will be released and I'll add a migration to auto update existing workspaces in a 11.0.1 or .2 patch by early next week.

**Comment by NathanWalker** [comment]
`11.0.0` is published now.

```
npx create-nx-workspace@latest
npm i @nstudio/xplat -D
nx g app
```

To create new workspaces with the new xplat lib separation.

I'll keep this PR open until I have the 11.0.1 migration complete which will provide a way to auto migrate existing Nx+xplat workspaces.

**Comment by NathanWalker** [comment]
For those looking to update existing Nx workspaces with xplat v10 to v11, we have published an rc that you can run this migration - we have tested this against several large workspaces internally with great results. Please try it and let us know:

* 1. Migrate Nx first

```
nx migrate latest
npm i
nx migrate --run-migrations=migrations.json
```

* 2. Migrate xplat and all @nstudio dev dependencies

To ensure all updates are installed prior to running migrations, gather all `@nstudio` devDependencies in your project and let's migrate each to latest.

*NOTE: The packages you update may differ depending on your xplat workspace but this shows an example of a workspace that had web and nativescript platforms configured. It will usually be all the `@nstudio` packages in `devDependencies`.*

```
nx migrate @nstudio/angular@11.0.3-rc.3
nx migrate @nstudio/nativescript-angular@11.0.3-rc.3
nx migrate @nstudio/nativescript@11.0.3-rc.3
nx migrate @nstudio/web-angular@11.0.3-rc.3 
nx migrate @nstudio/web@11.0.3-rc.3
nx migrate @nstudio/xplat@11.0.3-rc.3

npm install
```

*IMPORTANT: Don't forget to run `npm install` at the end.*

Now that the latest versions installed, kick off the xplat architecture **init** to add the new xplat lib separations.

You will want to pass just the **platforms** which you currently use in your workspace.
The **prefix** you use can be the same your workspace is currently configured to use. This can be found in `package.json` under the `xplat` key.

```
nx g @nstudio/xplat:init --prefix=abc --platforms=web,nativescript --framework=angular
```

With the new architecture in place and the latest all installed, you can now kick off the workspace migration:

```
nx migrate --run-migrations=migrations.json
```

This will handle **a lot** of laborious manual update tasks like:
* Updating your tsconfig path mappings
* Updating imports throughout all shared and app code to match the new xplat lib barrels
* Update app configurations to use the latest Nx 11 has to offer
* Update nx.json and workspace to clean out old retired references and update to new ones
* Lastly move all your shared code into the new structure

Lastly do a full clean of your workspace to ensure you're in good updated shape now:

```
npm run clean
```

We will publish a blog about this update and instructions soon but would greatly appreciate those looking to migrate existing workspaces and let us know.

**Pull request merged**
