### PR TITLE
feat(nestjs): init support for nestjs framework

### PR DESCRIPTION
**Pull request by miguelramos**
@NathanWalker hope your Christmas  was awesome with your family. Again after been working on apps i've realize that having backend services outside this structure start to makes no sense because if can have the same source code running thru BE and FE sharing resources that fit both worlds will be amazing. In this request i've found a long time ago this framework that is opinionated like angular and i think could be a good choice having inside of xplat ([nestjs](https://nestjs.com/)). ~~So i've initiated a schematic for it and i would like to have your support because i'm missing the code to give installation of the packages. I've added to the scripts array to install dependencies but when i use the command~~
 
```
ng g app.nestjs rest
```
~~they are not installed~~. Resolved the issue in one of the commits.

Please comment about this feature. If you think could be integrated or not and if you can help me finish this issue.

~~I'm think for initial this litte 'hello world' and them add support for all packages that nestjs has like: typeorm, microservices, websockets etc~~.

Send your inputs mate!!! And happy new year!!! .-)

Current: ready to use (i think) :).

### CODE REVIEW

**Comment by NathanWalker** [comment]
@miguelramos this is looking great! Been a nice holiday thank you. I'll look over this more in the coming days but initially this direction looks quite nice 🙏

**Comment by miguelramos** [comment]
> @miguelramos this is looking great! Been a nice holiday thank you. I'll look over this more in the coming days but initially this direction looks quite nice 🙏

Ok mate. Take your time. For now i've added almost everything to support the feature. Some things have to be done after install, for example the choice of the database driver the developer have to install manually but the initial support is done. Cheers!

**Comment by NathanWalker** [comment]
@miguelramos let’s change the platform name to just ‘nest’ since the js suffix is probably a bit redundant since xplat serves JS based frameworks. It’s also consistent to how the framework is official referred:

> Nest is a framework for building efficient...

👍 so just `ng g app.nest rest`

**Comment by miguelramos** [comment]
@NathanWalker applied the changes on the name of the app. 👍

**Pull request merged**
