### PR TITLE
remove isCapacitorNative import

### PR DESCRIPTION
**Pull request by vance**
this import actually breaks when adding platforms to ionic

### CODE REVIEW

**Comment by NathanWalker** [comment]
Excellent thank you @vance - when you get chance you might try bumping the devDependencies to solve the unit testing issue?:
```
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(36,40): error TS1144: '{' or ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(37,5): error TS1128: Declaration or statement expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(37,27): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(37,34): error TS1005: ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(38,5): error TS1128: Declaration or statement expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(38,32): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(38,39): error TS1005: ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(39,5): error TS1128: Declaration or statement expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(39,27): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(39,34): error TS1005: ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(40,5): error TS1128: Declaration or statement expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(40,25): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(40,32): error TS1005: ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(40,63): error TS1005: '(' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(40,69): error TS1005: ')' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(41,5): error TS1128: Declaration or statement expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(41,26): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(41,42): error TS1109: Expression expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(41,61): error TS1005: ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(41,89): error TS1005: '(' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(42,16): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(42,33): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(42,42): error TS1005: ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(42,48): error TS1109: Expression expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(43,15): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(43,24): error TS1005: ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(44,15): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(44,24): error TS1005: ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(45,17): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(45,26): error TS1005: ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(46,22): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(46,31): error TS1005: ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(47,17): error TS1005: ',' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(47,26): error TS1005: ';' expected.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(48,1): error TS1128: Declaration or statement expected.
```

**Comment by vance** [comment]
Looks like I bailed before CI finished. When I run locally, I don't get any errors, however. I tried bumping `@angular-devkit/core` and `@angular-devkit/schematics` and `@schematics/angular` to 7.0.1 and got a load of ast errors. I think this is out of scope for my capacity atm. One notable change is bumping angular versions changes `angular-cli.json` -> `angular.json`

```
Randomized with seed 42994
Started
..................................
34 specs, 0 failures
Finished in 4.446 seconds
Randomized with seed 42994 (jasmine --random=true --seed=42994)
```

**Comment by vance** [comment]
When I bumped devkit:

```
An issue was detected during installation: angular.json does not exist.
An issue were detected during patching the nx-formatter { Error: ENOENT: no such file or directory, open '/Users/@nrwl/schematics/src/command-line/format.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at fixFormatter (/Users/m82878/xplat/scripts/postinstall.js:38:28)
    at updateConfig (/Users/m82878/xplat/scripts/postinstall.js:28:9)
    at Object.<anonymous> (/Users/m82878/xplat/scripts/postinstall.js:35:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/@nrwl/schematics/src/command-line/format.js' }
$ npm run build

> @nstudio/schematics@6.2.9 build /Users/m82878/xplat
> tsc -p tsconfig.json

src/app-resources/index.ts:9:3 - error TS2305: Module '"/Users/m82878/xplat/node_modules/@angular-devkit/schematics/src/index"' has no exported member 'TemplateOptions'.

9   TemplateOptions
    ~~~~~~~~~~~~~~~


src/app.ionic/index.ts:11:3 - error TS2305: Module '"/Users/m82878/xplat/node_modules/@angular-devkit/schematics/src/index"' has no exported member 'TemplateOptions'.

11   TemplateOptions,
     ~~~~~~~~~~~~~~~


src/app.nativescript/index.ts:11:3 - error TS2305: Module '"/Users/m82878/xplat/node_modules/@angular-devkit/schematics/src/index"' has no exported member 'TemplateOptions'.

11   TemplateOptions,
     ~~~~~~~~~~~~~~~


src/app.web/index.ts:11:3 - error TS2305: Module '"/Users/m82878/xplat/node_modules/@angular-devkit/schematics/src/index"' has no exported member 'TemplateOptions'.

11   TemplateOptions,
     ~~~~~~~~~~~~~~~


src/component/index.ts:8:3 - error TS2305: Module '"/Users/m82878/xplat/node_modules/@angular-devkit/schematics/src/index"' has no exported member 'TemplateOptions'.

8   TemplateOptions,
    ~~~~~~~~~~~~~~~


src/feature/index.ts:8:3 - error TS2305: Module '"/Users/m82878/xplat/node_modules/@angular-devkit/schematics/src/index"' has no exported member 'TemplateOptions'.

8   TemplateOptions,
    ~~~~~~~~~~~~~~~


src/utils/ast.ts:40:38 - error TS2345: Argument of type 'ts.SourceFile' is not assignable to parameter of type 'ts.SourceFile'.
  Property 'libReferenceDirectives' is missing in type 'SourceFile'.

40   const nodes = getDecoratorMetadata(source, 'NgModule', '@angular/core');
                                        ~~~~~~


src/utils/ast.ts:214:38 - error TS2345: Argument of type 'ts.SourceFile' is not assignable to parameter of type 'ts.SourceFile'.
...more errors
```

**Comment by NathanWalker** [comment]
I just pushed this directly and it's published in `6.2.11` now. 👍

**Pull request closed without merging**
