### PR TITLE
feat(Testing): Adds testing/nativescript for unit testing (WIP)

### PR DESCRIPTION
**Pull request by m-abs**
Implements #33 

NativeScript tests expects tests to be inside app/tests.
To work around this, the before-prepare hook `import-specs-hook.js` generates the file `app/tests/import.spec.ts` which imports all spec-files from `@npmScope/nativescript`

I've added four scripts to the root `package.json`:
`test:android`, `test:android:watch`, `test:ios` and `test:ios:watch`

**Note:** TestBed wrapper from `nativescript/testing` is required for running the tests under nativescript. This means shared services cannot be tested in nativescript.

Missing:
- [ ] Migration scripts to create the test-app, add the npm scripts to the root `package.json`
- [ ] Generate `*.spec.ts` files for nativescript (They must use TestBed wrappers from `nativescript/testing`):
  - [x] components
  - [ ] pipes
  - [ ] directives
  - [ ]  services
- [x] Helpers for loading common modules like EffectsModule, StoreModule, NxModule etc.
- [ ] Tests for the sample-components? 
- [ ] First test run skips all the tests, looks like a timing issue.
- [x] Can't test components that depend on the router: https://github.com/NativeScript/nativescript-angular/issues/1549 
- [ ] How should we handle additional nativescript-plugins?
- [x] Update vscode settings to ignore `testing/nativescript/platforms`
- [ ] VSCode keeps crawling the `testing/nativescript/platforms`-folder during `tns test`.

### CODE REVIEW

**Comment by m-abs** [comment]
@NathanWalker 
Do you have an idea what to do about VSCode?
It keeps crawling the `testing/nativescript/platforms`-folder resulting in an extremely slow editor.

**Comment by NathanWalker** [comment]
@m-abs i'm going to take a look at this branch today and see what I can find out 👍

**Comment by NathanWalker** [comment]
I rebased master on here and investigating a few things.

**Comment by NathanWalker** [comment]
@m-abs this was an incredible effort and definitely provided some insight into a way this could be done and I ❤️ for it.  - We're going to try a slimmer approach to bringing unit testing with a bit less surface area and will close this now. Sometime soon perhaps we can collab together to leverage some ideas here into a new direction 🤗

**Pull request closed without merging**
